services:
  centos7:
    image: centos/python-38-centos7:latest
    container_name: centos7
    command: tail -f

  ubuntu:
    build: 
      dockerfile: Dockerfile_ubuntu
    image: ubuntu:20.04
    container_name: ubuntu
    command: tail -f

  fedora:
    image: pycontribs/fedora:latest
    container_name: fedora
    command: tail -f
